packages:
  - "apps/*"
  - "packages/*"

node-linker: hoisted

allowBuilds:
  esbuild: true
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  bcrypt: true
  sharp: true

minimumReleaseAgeExclude:
  - nodemailer@9.0.4
