import fs from "fs/promises";
import path from "path";
import * as acme from "acme-client";
import { prisma } from "./prisma.js";
import { getEnv } from "../config/env.js";

interface AcmeChallengeEntry {
  keyAuthorization: string;
  createdAt: number;
}

export const acmeChallenges = new Map<string, AcmeChallengeEntry>();

const ACME_CHALLENGE_TTL_MS = 10 * 60 * 1000;

function pruneAcmeChallenges(): void {
  const cutoff = Date.now() - ACME_CHALLENGE_TTL_MS;
  for (const [token, entry] of acmeChallenges) {
    if (entry.createdAt < cutoff) acmeChallenges.delete(token);
  }
}

const NGINX_CERTS_ROOT = "/etc/nginx/certs";
const NGINX_CONF_NAME = "custom-domains.conf";

const ACME_RETRY_BACKOFF_MS = 60 * 60 * 1000;

export function acmeEnabled(): boolean {
  return getEnv().ACME_ENABLED;
}

function certsPath(): string {
  return path.resolve(getEnv().ACME_CERTS_PATH);
}

function domainDir(domain: string): string {
  return path.join(certsPath(), domain);
}

function nginxConfPath(): string {
  return path.join(certsPath(), NGINX_CONF_NAME);
}

function certFiles(domain: string) {
  return {
    cert: path.join(domainDir(domain), "cert.pem"),
    key: path.join(domainDir(domain), "key.pem"),
  };
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function loadOrCreateAccountKey(): Promise<Buffer | string> {
  const dir = path.join(certsPath(), "acme");
  const file = path.join(dir, "account.key");
  if (await exists(file)) {
    return fs.readFile(file, "utf8");
  }
  const key = await acme.crypto.createPrivateEcdsaKey();
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(file, key, { mode: 0o600 });
  return key;
}

export function hasCertFiles(domain: string): Promise<boolean> {
  const { cert, key } = certFiles(domain);
  return Promise.all([exists(cert), exists(key)]).then(([c, k]) => c && k);
}

async function writeFilesAtomic(domain: string, certificate: string, privateKey: string | Buffer): Promise<void> {
  const dir = domainDir(domain);
  const { cert, key } = certFiles(domain);
  await fs.mkdir(dir, { recursive: true });
  const tmpCert = `${cert}.tmp`;
  const tmpKey = `${key}.tmp`;
  await fs.writeFile(tmpCert, certificate, { mode: 0o600 });
  await fs.writeFile(tmpKey, privateKey, { mode: 0o600 });
  await fs.rename(tmpCert, cert);
  await fs.rename(tmpKey, key);
}

export async function buildNginxCustomDomainsConf(domains: Array<{ domain: string; tlsStatus: string }>): Promise<string> {
  const enabled = acmeEnabled();
  const lines: string[] = ["# Auto-generated by the backend ACME service. Do not edit manually."];

  for (const entry of domains) {
    const domain = entry.domain.toLowerCase().replace(/\.$/, "");
    if (!/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(domain)) {
      continue;
    }
    const certDir = `${NGINX_CERTS_ROOT}/${domain}`;
    const certOk = entry.tlsStatus === "ISSUED" && (await hasCertFiles(domain));
    if (!certOk && !enabled) {
      continue;
    }

    lines.push("server {", "    listen 80;", "    listen [::]:80;", `    server_name ${domain} www.${domain};`);
    lines.push("    location /.well-known/acme-challenge/ {");
    lines.push("        proxy_pass http://backend;");
    lines.push("        proxy_http_version 1.1;");
    lines.push("        proxy_set_header Host $host;");
    lines.push("    }");
    lines.push("    location / {");
    lines.push("        return 301 https://$host$request_uri;");
    lines.push("    }");
    lines.push("}");

    if (certOk) {
      lines.push(
        "server {",
        "    listen 443 ssl;",
        "    listen [::]:443 ssl;",
        "    http2 on;",
        `    server_name ${domain} www.${domain};`,
        `    ssl_certificate ${certDir}/cert.pem;`,
        `    ssl_certificate_key ${certDir}/key.pem;`,
        "    ssl_protocols TLSv1.2 TLSv1.3;",
        "    ssl_ciphers HIGH:!aNULL:!MD5;",
        "    ssl_prefer_server_ciphers on;",
        "    ssl_session_cache shared:SSL:10m;",
        "    ssl_session_timeout 10m;",
        "    include /etc/nginx/conf.d/hsts.conf;",
        "    include /etc/nginx/custom/site.conf;",
        "}"
      );
    }
  }

  return lines.join("\n") + "\n";
}

export async function regenerateNginxConf(): Promise<void> {
  const active = await prisma.profileDomain.findMany({
    where: { status: "ACTIVE" },
    select: { domain: true, tlsStatus: true },
  });
  const content = await buildNginxCustomDomainsConf(active.map((e) => ({ domain: e.domain, tlsStatus: e.tlsStatus })));
  await fs.mkdir(certsPath(), { recursive: true });
  await fs.writeFile(nginxConfPath(), content, "utf8");
}

export function getChallenge(token: string): string | undefined {
  pruneAcmeChallenges();
  const entry = acmeChallenges.get(token);
  return entry?.keyAuthorization;
}

async function issueCertificateForDomain(domain: string): Promise<{ ok: boolean; message: string }> {
  const env = getEnv();
  const entry = await prisma.profileDomain.findUnique({ where: { domain } });
  if (!entry) return { ok: false, message: "Domain not found." };
  if (entry.status !== "ACTIVE") {
    return { ok: false, message: `Only ACTIVE domains can get a certificate (current status: ${entry.status}).` };
  }
  if (!env.ACME_ENABLED) {
    return { ok: false, message: "ACME is disabled (set ACME_ENABLED=true)." };
  }

  const error = (message: string) =>
    prisma.profileDomain
      .update({ where: { id: entry.id }, data: { tlsStatus: "FAILED", tlsError: message.slice(0, 500) } })
      .then(() => ({ ok: false, message }))
      .catch(() => ({ ok: false, message }));

  try {
    await prisma.profileDomain.update({
      where: { id: entry.id },
      data: { tlsStatus: "PENDING", tlsError: null },
    });

    const accountKey = await loadOrCreateAccountKey();
    const client = new acme.Client({
      directoryUrl: env.ACME_DIRECTORY_URL,
      accountKey,
    });

    const [privateKey, csr] = await acme.crypto.createCsr({
      keySize: 2048,
      altNames: [domain, `www.${domain}`],
    });

    const cert = await client.auto({
      csr,
      email: env.ACME_EMAIL || undefined,
      termsOfServiceAgreed: true,
      challengeCreateFn: async (_authz, challenge, keyAuthorization) => {
        acmeChallenges.set(challenge.token, { keyAuthorization, createdAt: Date.now() });
        pruneAcmeChallenges();
      },
      challengeRemoveFn: async (_authz, challenge) => {
        acmeChallenges.delete(challenge.token);
      },
    });

    await writeFilesAtomic(domain, cert, privateKey);

    let expiresAt: Date | null = null;
    try {
      const info = acme.crypto.readCertificateInfo(cert);
      expiresAt = new Date(info.notAfter);
    } catch {
      expiresAt = new Date(Date.now() + 90 * 24 * 60 * 60 * 1000);
    }

    await prisma.profileDomain.update({
      where: { id: entry.id },
      data: { tlsStatus: "ISSUED", tlsIssuedAt: new Date(), tlsExpiresAt: expiresAt, tlsError: null },
    });
    await regenerateNginxConf();

    return { ok: true, message: `Certificate issued for ${domain}.` };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[acme] issuance failed for ${domain}:`, err);
    return error(message);
  }
}

export { issueCertificateForDomain };

let loopRunning = false;
let loopTimer: NodeJS.Timeout | null = null;

export async function acmeTick(): Promise<void> {
  if (loopRunning) return;
  loopRunning = true;
  try {
    await regenerateNginxConf();
    if (!acmeEnabled()) return;
    const env = getEnv();
    const renewBeforeMs = env.ACME_RENEW_BEFORE_DAYS * 24 * 60 * 60 * 1000;
    const now = Date.now();
    const renewBy = new Date(now + renewBeforeMs);
    const retryBackoffBefore = new Date(now - ACME_RETRY_BACKOFF_MS);

    const renewals = await prisma.profileDomain.findMany({
      where: {
        status: "ACTIVE",
        tlsStatus: "ISSUED",
        tlsExpiresAt: { not: null, lte: renewBy },
      },
      orderBy: { tlsExpiresAt: "asc" },
      take: env.ACME_MAX_DOMAINS_PER_RUN,
    });

    const remaining = env.ACME_MAX_DOMAINS_PER_RUN - renewals.length;
    let retries: typeof renewals = [];
    if (remaining > 0) {
      retries = await prisma.profileDomain.findMany({
        where: {
          status: "ACTIVE",
          NOT: { tlsStatus: "ISSUED" },
          OR: [{ tlsStatus: "NONE" }, { updatedAt: { lt: retryBackoffBefore } }],
        },
        orderBy: { updatedAt: "asc" },
        take: remaining,
      });
    }

    for (const entry of [...renewals, ...retries]) {
      const hasFiles = await hasCertFiles(entry.domain);
      const issued = entry.tlsStatus === "ISSUED";
      const expiringSoon =
        entry.tlsExpiresAt !== null && entry.tlsExpiresAt.getTime() - now < renewBeforeMs;
      if (hasFiles && issued && !expiringSoon) continue;
      const result = await issueCertificateForDomain(entry.domain);
      console.log(`[acme] ${entry.domain}: ${result.message}`);
    }
  } catch (err) {
    console.error("[acme] tick failed:", err);
  } finally {
    loopRunning = false;
  }
}

export function startAcmeLoop(): void {
  if (loopTimer) return;
  const env = getEnv();
  void acmeTick();
  loopTimer = setInterval(() => {
    void acmeTick();
  }, env.ACME_INTERVAL_MINUTES * 60 * 1000);
}
