#!/bin/sh
set -e

mode=${TLS_MODE:-development}
send_hsts_on_dev=${SEND_HSTS_ON_DEV:-false}
dir=/etc/nginx/certs
self_cert=$dir/self-signed.pem
self_key=$dir/self-signed.key
cert=$dir/cert.pem
key=$dir/key.pem

have_openssl=0
if command -v openssl >/dev/null 2>&1; then
  have_openssl=1
fi

is_valid() {
  [ -f "$cert" ] && [ -f "$key" ] || return 1
  if [ "$have_openssl" = "1" ]; then
    openssl x509 -in "$cert" -noout -checkend 0 >/dev/null 2>&1 || return 1
    openssl x509 -in "$cert" -noout -pubkey >/dev/null 2>&1 || return 1
  fi
  return 0
}

remove_dev_certs() {
  rm -f "$self_cert" "$self_key"
  if [ -L "$cert" ]; then rm -f "$cert"; fi
  if [ -L "$key" ]; then rm -f "$key"; fi
}

case "$mode" in
  production)
    remove_dev_certs
    if ! is_valid; then
      echo "TLS_MODE=production requires a valid certificate/key pair." >&2
      echo "Place cert.pem and key.pem in ./certs/ (self-signed development certs are removed automatically)." >&2
      echo "Set TLS_MODE=development to auto-generate self-signed certs." >&2
      exit 1
    fi
    ;;
  *)
    remove_dev_certs
    if ! is_valid; then
      if [ "$have_openssl" = "0" ]; then
        echo "Installing openssl to generate a self-signed certificate..."
        apk add --no-cache openssl >/dev/null 2>&1 || exit 1
      fi
      echo "Generating self-signed certificate (development mode)..."
      openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
        -keyout "$self_key" -out "$self_cert" \
        -subj "/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"
      ln -sf self-signed.pem "$cert"
      ln -sf self-signed.key "$key"
      echo "Self-signed certificate generated: $self_cert (symlinked to cert.pem/key.pem)"
    fi
    ;;
esac

hsts_conf=/etc/nginx/conf.d/hsts.conf
if [ "$mode" = "production" ] || [ "$send_hsts_on_dev" = "true" ]; then
  printf 'add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;\n' > "$hsts_conf"
else
  printf '# HSTS disabled (development mode, SEND_HSTS_ON_DEV not true)\n' > "$hsts_conf"
fi

# Restore the real client IP from the standard X-Forwarded-For chain.
# This works with any reverse proxy in front (Cloudflare Tunnel, Nginx,
# Caddy, Traefik, HAProxy, ...) as long as it appends the client IP to
# X-Forwarded-For. Only trust sources the proxy connects from
# (docker bridge gateway + loopback), so direct clients cannot spoof it.
real_ip_conf=/etc/nginx/conf.d/real_ip.conf
trusted_ips=${CF_TRUSTED_IPS:-172.16.0.0/12,127.0.0.1,::1}
{
  for ip in $(printf '%s\n' "$trusted_ips" | tr ',' ' '); do
    [ -n "$ip" ] && printf 'set_real_ip_from %s;\n' "$ip"
  done
  printf 'real_ip_header X-Forwarded-For;\n'
  printf 'real_ip_recursive on;\n'
} > "$real_ip_conf"

# Custom-domain server blocks are generated and managed by the backend ACME
# service (certificates + nginx config in the shared certs volume). We only
# ensure the include file exists so nginx starts cleanly, and watch it for
# changes so the backend can drop certs/config and trigger a reload.
custom_conf=/etc/nginx/certs/custom-domains.conf
[ -f "$custom_conf" ] || printf '# Custom domain config is generated by the backend ACME service.\n' > "$custom_conf"

# Watch the backend-managed custom-domains.conf and reload nginx when it
# changes (new certificate issued, domain activated, etc.).
reload_watcher() {
  last=0
  while :; do
    if [ -f "$custom_conf" ]; then
      now=$(stat -c %Y "$custom_conf" 2>/dev/null || printf '0')
      if [ "$now" != "$last" ]; then
        last=$now
        sleep 2
        if nginx -t >/dev/null 2>&1; then
          nginx -s reload >/dev/null 2>&1 || true
        else
          echo "custom-domains: nginx config test failed after reload trigger" >&2
        fi
      fi
    fi
    sleep 3
  done
}
reload_watcher &

# Map that tells nginx whether the request host is the app's own domain.
# Used to send social crawlers hitting the ROOT of a custom domain to the
# backend (server-rendered OG) while the app host keeps its static SPA OG.
app_host_conf=/etc/nginx/conf.d/app-host.conf
app_host=${APP_URL_HOST:-}
{
  printf '# App host map (generated at startup)\n'
  printf 'map $host $is_app_host {\n'
  printf '    default 0;\n'
  if [ -n "$app_host" ]; then
    printf '    %s 1;\n' "$app_host"
    case "$app_host" in
      www.*)
        printf '    %s 1;\n' "$(printf '%s' "$app_host" | cut -c5-)"
        ;;
      *)
        printf '    www.%s 1;\n' "$app_host"
        ;;
    esac
  fi
  printf '}\n'
} > "$app_host_conf"

exec /docker-entrypoint.sh "$@"
